/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hp_hpl_palette_similarity_bridge_HashIndexProxy */

#ifndef _Included_com_hp_hpl_palette_similarity_bridge_HashIndexProxy
#define _Included_com_hp_hpl_palette_similarity_bridge_HashIndexProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hp_hpl_palette_similarity_bridge_HashIndexProxy
 * Method:    getMemoryOccupied
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_com_hp_hpl_palette_similarity_bridge_HashIndexProxy_getMemoryOccupied
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_hp_hpl_palette_similarity_bridge_HashIndexProxy
 * Method:    postProcessing
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_hp_hpl_palette_similarity_bridge_HashIndexProxy_postProcessing
  (JNIEnv *, jobject, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
