/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hp_hpl_palette_similarity_bridge_LSHManagerProxy */

#ifndef _Included_com_hp_hpl_palette_similarity_bridge_LSHManagerProxy
#define _Included_com_hp_hpl_palette_similarity_bridge_LSHManagerProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hp_hpl_palette_similarity_bridge_LSHManagerProxy
 * Method:    startLSHManager
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_com_hp_hpl_palette_similarity_bridge_LSHManagerProxy_startLSHManager
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_hp_hpl_palette_similarity_bridge_LSHManagerProxy
 * Method:    setLSHHashStruct
 * Signature: (IJJ)V
 */
JNIEXPORT void JNICALL Java_com_hp_hpl_palette_similarity_bridge_LSHManagerProxy_setLSHHashStruct
  (JNIEnv *, jobject, jint, jlong, jlong);

/*
 * Class:     com_hp_hpl_palette_similarity_bridge_LSHManagerProxy
 * Method:    changeRval
 * Signature: (IJF)V
 */
JNIEXPORT void JNICALL Java_com_hp_hpl_palette_similarity_bridge_LSHManagerProxy_changeRval
  (JNIEnv *, jobject, jint, jlong, jfloat);

/*
 * Class:     com_hp_hpl_palette_similarity_bridge_LSHManagerProxy
 * Method:    constructCompactTs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hp_hpl_palette_similarity_bridge_LSHManagerProxy_constructCompactTs
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
