/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hp_hpl_palette_similarity_bridge_TimeSeriesBuilderProxy */

#ifndef _Included_com_hp_hpl_palette_similarity_bridge_TimeSeriesBuilderProxy
#define _Included_com_hp_hpl_palette_similarity_bridge_TimeSeriesBuilderProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hp_hpl_palette_similarity_bridge_TimeSeriesBuilderProxy
 * Method:    buildTimeSeries
 * Signature: (JI[F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_hp_hpl_palette_similarity_bridge_TimeSeriesBuilderProxy_buildTimeSeries
  (JNIEnv *, jobject, jlong, jint, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
