/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hp_hpl_palette_similarity_bridge_IndexBuilderProxy */

#ifndef _Included_com_hp_hpl_palette_similarity_bridge_IndexBuilderProxy
#define _Included_com_hp_hpl_palette_similarity_bridge_IndexBuilderProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hp_hpl_palette_similarity_bridge_IndexBuilderProxy
 * Method:    buildIndex
 * Signature: (JIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_hp_hpl_palette_similarity_bridge_IndexBuilderProxy_buildIndex
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     com_hp_hpl_palette_similarity_bridge_IndexBuilderProxy
 * Method:    setHashTableType
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_hp_hpl_palette_similarity_bridge_IndexBuilderProxy_setHashTableType
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_hp_hpl_palette_similarity_bridge_IndexBuilderProxy
 * Method:    serialize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_hp_hpl_palette_similarity_bridge_IndexBuilderProxy_serialize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_hp_hpl_palette_similarity_bridge_IndexBuilderProxy
 * Method:    deserialize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_hp_hpl_palette_similarity_bridge_IndexBuilderProxy_deserialize
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
