/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lsh_LSHinf */

#ifndef _Included_lsh_LSHinf
#define _Included_lsh_LSHinf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lsh_LSHinf
 * Method:    initHashIndex
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_lsh_LSHinf_initHashIndex
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     lsh_LSHinf
 * Method:    put
 * Signature: (JIIIII[I[I)V
 */
JNIEXPORT void JNICALL Java_lsh_LSHinf_put
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint, jintArray, jintArray);

/*
 * Class:     lsh_LSHinf
 * Method:    getCount
 * Signature: (JIII[I[I)I
 */
JNIEXPORT jint JNICALL Java_lsh_LSHinf_getCount
  (JNIEnv *, jobject, jlong, jint, jint, jint, jintArray, jintArray);

/*
 * Class:     lsh_LSHinf
 * Method:    get
 * Signature: (JIII[I[I[I[I)V
 */
JNIEXPORT void JNICALL Java_lsh_LSHinf_get
  (JNIEnv *, jobject, jlong, jint, jint, jint, jintArray, jintArray, jintArray, jintArray);

/*
 * Class:     lsh_LSHinf
 * Method:    initLSH
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_lsh_LSHinf_initLSH
  (JNIEnv *, jobject);

/*
 * Class:     lsh_LSHinf
 * Method:    initHash
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_lsh_LSHinf_initHash
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     lsh_LSHinf
 * Method:    deserializeLSH
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_lsh_LSHinf_deserializeLSH
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     lsh_LSHinf
 * Method:    deserializeHash
 * Signature: (IJ[B)J
 */
JNIEXPORT jlong JNICALL Java_lsh_LSHinf_deserializeHash
  (JNIEnv *, jobject, jint, jlong, jbyteArray);

/* * Class:     lsh_LSHinf
 * Method:    getHashIndex
 * Signature: (JJ[D[I[II)V
 */
JNIEXPORT void JNICALL Java_lsh_LSHinf_getHashIndex
  (JNIEnv *, jobject, jlong, jlong, jdoubleArray, jintArray, jintArray, jint);

/*
 * Class:     lsh_LSHinf
 * Method:    getPerturbationCnt
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_lsh_LSHinf_getPerturbationCnt
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     lsh_LSHinf
 * Method:    getPerturbationIndices
 * Signature: (JJ[D[I[III)V
 */
JNIEXPORT void JNICALL Java_lsh_LSHinf_getPerturbationIndices
  (JNIEnv *, jobject, jlong, jlong, jdoubleArray, jintArray, jintArray, jint, jint);

/*
 * Class:     lsh_LSHinf
 * Method:    getSizeSerializedLSH
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_lsh_LSHinf_getSizeSerializedLSH
  (JNIEnv *, jobject, jlong);

/*
 * Class:     lsh_LSHinf
 * Method:    getSizeSerializedHash
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_lsh_LSHinf_getSizeSerializedHash
  (JNIEnv *, jobject, jlong);

/*
 * Class:     lsh_LSHinf
 * Method:    serializeLSH
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_lsh_LSHinf_serializeLSH
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     lsh_LSHinf
 * Method:    serializeHash
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_lsh_LSHinf_serializeHash
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     lsh_LSHinf
 * Method:    cleanup
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_lsh_LSHinf_cleanup
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
